<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.475">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Maria del Mar Deyà Torrens">
<meta name="author" content="Toni Fuentes Bauzá">
<meta name="author" content="Frank William Hammond Espinosa">

<title>Entrega 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="entrega1_files/libs/clipboard/clipboard.min.js"></script>
<script src="entrega1_files/libs/quarto-html/quarto.js"></script>
<script src="entrega1_files/libs/quarto-html/popper.min.js"></script>
<script src="entrega1_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="entrega1_files/libs/quarto-html/anchor.min.js"></script>
<link href="entrega1_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="entrega1_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="entrega1_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="entrega1_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="entrega1_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#exploración-inicial-y-descripción-de-variables." id="toc-exploración-inicial-y-descripción-de-variables." class="nav-link active" data-scroll-target="#exploración-inicial-y-descripción-de-variables.">Exploración inicial y descripción de variables.</a>
  <ul class="collapse">
  <li><a href="#especie" id="toc-especie" class="nav-link" data-scroll-target="#especie">Especie</a></li>
  <li><a href="#isla" id="toc-isla" class="nav-link" data-scroll-target="#isla">Isla</a></li>
  <li><a href="#longitud-del-pico" id="toc-longitud-del-pico" class="nav-link" data-scroll-target="#longitud-del-pico">Longitud del pico</a></li>
  <li><a href="#profundidad-del-pico" id="toc-profundidad-del-pico" class="nav-link" data-scroll-target="#profundidad-del-pico">Profundidad del pico</a></li>
  <li><a href="#longitud-de-la-aleta" id="toc-longitud-de-la-aleta" class="nav-link" data-scroll-target="#longitud-de-la-aleta">Longitud de la aleta</a></li>
  <li><a href="#peso" id="toc-peso" class="nav-link" data-scroll-target="#peso">Peso</a></li>
  <li><a href="#sexo" id="toc-sexo" class="nav-link" data-scroll-target="#sexo">Sexo</a></li>
  <li><a href="#año" id="toc-año" class="nav-link" data-scroll-target="#año">Año</a></li>
  </ul></li>
  <li><a href="#datos-demográficos" id="toc-datos-demográficos" class="nav-link" data-scroll-target="#datos-demográficos">Datos demográficos</a>
  <ul class="collapse">
  <li><a href="#distribución-de-pingüinos-según-la-isla" id="toc-distribución-de-pingüinos-según-la-isla" class="nav-link" data-scroll-target="#distribución-de-pingüinos-según-la-isla">Distribución de pingüinos según la isla</a></li>
  </ul></li>
  <li><a href="#variables-cuantitativas-por-especie" id="toc-variables-cuantitativas-por-especie" class="nav-link" data-scroll-target="#variables-cuantitativas-por-especie">Variables cuantitativas por especie</a>
  <ul class="collapse">
  <li><a href="#comparación-una-a-una" id="toc-comparación-una-a-una" class="nav-link" data-scroll-target="#comparación-una-a-una">Comparación una a una</a></li>
  <li><a href="#comparación-entre-ellas-y-por-especie" id="toc-comparación-entre-ellas-y-por-especie" class="nav-link" data-scroll-target="#comparación-entre-ellas-y-por-especie">Comparación entre ellas y por especie</a></li>
  </ul></li>
  <li><a href="#diferencias-entre-pingüinos-según-el-sexo" id="toc-diferencias-entre-pingüinos-según-el-sexo" class="nav-link" data-scroll-target="#diferencias-entre-pingüinos-según-el-sexo">Diferencias entre pingüinos según el sexo</a></li>
  <li><a href="#variables-cuantitativas-por-isla" id="toc-variables-cuantitativas-por-isla" class="nav-link" data-scroll-target="#variables-cuantitativas-por-isla">Variables cuantitativas por isla</a></li>
  <li><a href="#métricas-por-año" id="toc-métricas-por-año" class="nav-link" data-scroll-target="#métricas-por-año">Métricas por año</a></li>
  <li><a href="#conclusión-y-resumen" id="toc-conclusión-y-resumen" class="nav-link" data-scroll-target="#conclusión-y-resumen">Conclusión y resumen</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Entrega 1</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autores/as</div>
    <div class="quarto-title-meta-contents">
             <p>Maria del Mar Deyà Torrens </p>
             <p>Toni Fuentes Bauzá </p>
             <p>Frank William Hammond Espinosa </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<p>Instalamos los paquetes que vamos a necesitar:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"palmerpenguins"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"corrplot"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"tidyr"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">

</div>
<section id="exploración-inicial-y-descripción-de-variables." class="level2">
<h2 class="anchored" data-anchor-id="exploración-inicial-y-descripción-de-variables.">Exploración inicial y descripción de variables.</h2>
<p>En primer lugar, visualizaremos el conjunto de datos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">%&gt;%</span> str</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [344 × 8] (S3: tbl_df/tbl/data.frame)
 $ species          : Factor w/ 3 levels "Adelie","Chinstrap",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ island           : Factor w/ 3 levels "Biscoe","Dream",..: 3 3 3 3 3 3 3 3 3 3 ...
 $ bill_length_mm   : num [1:344] 39.1 39.5 40.3 NA 36.7 39.3 38.9 39.2 34.1 42 ...
 $ bill_depth_mm    : num [1:344] 18.7 17.4 18 NA 19.3 20.6 17.8 19.6 18.1 20.2 ...
 $ flipper_length_mm: int [1:344] 181 186 195 NA 193 190 181 195 193 190 ...
 $ body_mass_g      : int [1:344] 3750 3800 3250 NA 3450 3650 3625 4675 3475 4250 ...
 $ sex              : Factor w/ 2 levels "female","male": 2 1 1 NA 1 2 1 2 NA NA ...
 $ year             : int [1:344] 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 ...</code></pre>
</div>
</div>
<div class="cell">

</div>
<p>El estudio se realizó escogiendo datos de tres especies distintas de pingüino en tres islas distintas del archipiélago Palmer, en la Antártida. Por tanto, la unidad muestral de la tabla es un pingüino.</p>
<p>Hay 344 observaciones de 8 variables, que son, por orden de aparición en el código anterior:</p>
<section id="especie" class="level3">
<h3 class="anchored" data-anchor-id="especie">Especie</h3>
<p>Esta variable registra la especie del ejemplar. Es cualitativa nominal politómica.</p>
<p>Hemos visto ya en la descripción del tibble que hay tres especies de pingüino. Para ver qué especies son y cuántos ejemplares hay de cada una, utilizamos el siguiente codigo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>x<span class="ot">=</span><span class="fu">table</span>(penguins<span class="sc">$</span>species)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(x,<span class="st">"NA's"</span><span class="ot">=</span><span class="fu">sum</span>(<span class="fu">is.na</span>(penguins<span class="sc">$</span>species)))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Adelie Chinstrap    Gentoo      NA's 
      152        68       124         0 </code></pre>
</div>
</div>
<p>Por tanto, de más a menos común, hay pingüinos de las especies <em>Adelie</em>, <em>Gentoo</em> y <em>Chinstrap</em>. No hay pingüinos sin clasificar por su especie.</p>
</section>
<section id="isla" class="level3">
<h3 class="anchored" data-anchor-id="isla">Isla</h3>
<p>Esta variable registra la isla en la que fue encontrado el ejemplar. Es cualitativa nominal politómica.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>x<span class="ot">=</span><span class="fu">table</span>(penguins<span class="sc">$</span>island)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(x,<span class="st">"NA's"</span><span class="ot">=</span><span class="fu">sum</span>(<span class="fu">is.na</span>(x)))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Biscoe     Dream Torgersen      NA's 
      168       124        52         0 </code></pre>
</div>
</div>
<p>De más a menos cantidad, hay pingüinos en las islas <em>Biscoe</em>, <em>Dream</em> y <em>Torgersen</em>. Tampoco hay ejemplares sin isla registrada.</p>
</section>
<section id="longitud-del-pico" class="level3">
<h3 class="anchored" data-anchor-id="longitud-del-pico">Longitud del pico</h3>
<p>Tanto esta variable como la siguiente en la lista se explican de manera sencilla con la siguiente ilustración:</p>
<p><img src="Explicacion_dimensiones_pico.png" class="img-fluid"></p>
<p>Es cuantitativa continua, está expresada en milímetros y discretizada a las décimas (<span class="math inline">\(10^{-4}\)</span> metros).</p>
<p>Veamos los estadísticos más comunes de esta variable:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  32.10   39.23   44.45   43.92   48.50   59.60       2 </code></pre>
</div>
</div>
<p>El pico más corto mide 32.1 milímetros, y el más largo, 59.6. El primer cuartil de esta variable es 39.225, la mediana 44.45 y el tercero 48.5. La media es de 43.9219298 y la desviación típica muestral de 5.4595837. Además, hay 2 valores NA.</p>
</section>
<section id="profundidad-del-pico" class="level3">
<h3 class="anchored" data-anchor-id="profundidad-del-pico">Profundidad del pico</h3>
<p>Es cuantitativa continua, está expresada en milímetros y discretizada a las décimas (<span class="math inline">\(10^{-4}\)</span> metros).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  13.10   15.60   17.30   17.15   18.70   21.50       2 </code></pre>
</div>
</div>
<p>El pico más fino mide 13.1 milímetros, y el más grueso, 21.5. El primer cuartil de esta variable es 15.6, la mediana 17.3 y el tercero 18.7. La media es de 17.1511696 y la desviación típica muestral de 5.4595837. Además, hay 2 valores NA.</p>
</section>
<section id="longitud-de-la-aleta" class="level3">
<h3 class="anchored" data-anchor-id="longitud-de-la-aleta">Longitud de la aleta</h3>
<p>El nombre de la variable explica claramente qué representa. Es cuantitativa continua, está expresada en milímetros y discretizada a las unidades (<span class="math inline">\(10^{-3}\)</span> metros).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  172.0   190.0   197.0   200.9   213.0   231.0       2 </code></pre>
</div>
</div>
<p>La aleta más corta mide 172 milímetros, y la más larga, 231. El primer cuartil de esta variable es 190, la mediana 197 y el tercero 213. La media es de 200.9152047 y la desviación típica muestral de 5.4595837. Además, hay 2 valores NA.</p>
</section>
<section id="peso" class="level3">
<h3 class="anchored" data-anchor-id="peso">Peso</h3>
<p>Es cuantitativa continua, está expresada en gramos y discretizada a los múltiplos de 5 gramos. Para ver que, efectivamente, esa es la discretización, hemos utilizado el siguiente código:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>pesos<span class="ot">=</span><span class="fu">na.omit</span>(penguins<span class="sc">$</span>body_mass_g)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(pesos<span class="sc">%%</span><span class="dv">5</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>Deducimos que no hay ningún dato que no sea múltiplo de 5 (si hubiese alguno, la suma sería <span class="math inline">\(&gt;0\)</span>).</p>
<p>Ahora veamos algunos estadísticos de esta variable:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
   2700    3550    4050    4202    4750    6300       2 </code></pre>
</div>
</div>
<p>El pingüino más liviano pesa 2700 gramos, y el más pesado, 6300. El primer cuartil de esta variable es 3550, la mediana 4050 y el tercero 4750. La media es de 4201.754386 y la desviación típica muestral de 5.4595837. Además, hay 2 valores NA.</p>
</section>
<section id="sexo" class="level3">
<h3 class="anchored" data-anchor-id="sexo">Sexo</h3>
<p>Registra si el pingüino es macho o hembra, salvo en algunos casos en los que no se determinó. Es cualitativa nominal dicotómica.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>x<span class="ot">=</span><span class="fu">table</span>(penguins<span class="sc">$</span>sex)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(x,<span class="st">"NA's"</span><span class="ot">=</span><span class="fu">sum</span>(<span class="fu">is.na</span>(penguins<span class="sc">$</span>sex)))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>female   male   NA's 
   165    168     11 </code></pre>
</div>
</div>
</section>
<section id="año" class="level3">
<h3 class="anchored" data-anchor-id="año">Año</h3>
<p>El año en el que se realizó el registro del pingüino. Esta variable es ordinal, pero R asigna a esta variable el tipo <code>int</code>, pues sus valores son números enteros. En realidad se trata de un factor ordenado. Podemos arreglar esto con el siguiente código:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>penguins<span class="sc">$</span>year<span class="ot">=</span><span class="fu">factor</span>(penguins<span class="sc">$</span>year, <span class="at">ordered=</span><span class="cn">TRUE</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">%&gt;%</span> str</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [344 × 8] (S3: tbl_df/tbl/data.frame)
 $ species          : Factor w/ 3 levels "Adelie","Chinstrap",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ island           : Factor w/ 3 levels "Biscoe","Dream",..: 3 3 3 3 3 3 3 3 3 3 ...
 $ bill_length_mm   : num [1:344] 39.1 39.5 40.3 NA 36.7 39.3 38.9 39.2 34.1 42 ...
 $ bill_depth_mm    : num [1:344] 18.7 17.4 18 NA 19.3 20.6 17.8 19.6 18.1 20.2 ...
 $ flipper_length_mm: int [1:344] 181 186 195 NA 193 190 181 195 193 190 ...
 $ body_mass_g      : int [1:344] 3750 3800 3250 NA 3450 3650 3625 4675 3475 4250 ...
 $ sex              : Factor w/ 2 levels "female","male": 2 1 1 NA 1 2 1 2 NA NA ...
 $ year             : Ord.factor w/ 3 levels "2007"&lt;"2008"&lt;..: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
</div>
<p>Ahora sí tiene el tipo adecuado.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>x<span class="ot">=</span><span class="fu">table</span>(penguins<span class="sc">$</span>year)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(x,<span class="st">"NA's"</span><span class="ot">=</span><span class="fu">sum</span>(<span class="fu">is.na</span>(penguins<span class="sc">$</span>year)))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2007 2008 2009 NA's 
 110  114  120    0 </code></pre>
</div>
</div>
<p>Se ha tomado, aproximadamente, el mismo número de muestras en cada año.</p>
<p>Una vez discutidas individualmente las variables, estudiaremos algunos datos demográficos, como la distribución de sexo por especie y de especie por isla:</p>
</section>
</section>
<section id="datos-demográficos" class="level2">
<h2 class="anchored" data-anchor-id="datos-demográficos">Datos demográficos</h2>
<p>Es sensato comprobar qué relación hay entre el sexo y las demás variables cualitativas (¿El año o la isla están sesgados por el sexo? ¿Las especies presentan una distribución 50/50 de machos y hembras?), pero por brevedad nos limitaremos a relacionarlo con la especie.</p>
<p>En los gráficos de abajo se puede apreciar la proporción de pinguinos de las distintas especies en cada isla:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="entrega1_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Vemos que en cada especie hay prácticamente la misma cantidad de machos que de hembras.</p>
<section id="distribución-de-pingüinos-según-la-isla" class="level3">
<h3 class="anchored" data-anchor-id="distribución-de-pingüinos-según-la-isla">Distribución de pingüinos según la isla</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="entrega1_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Vemos que la especie Gentoo se encuentra únicamente en la isla Biscoe y Chinstrap está solo en Dream. Por otra parte, Adelie se puede encontrar en las tres islas.</p>
<p>Se puede observar que en función de la isla que tratemos, habitan pingüinos de una especie u otra:</p>
<ul>
<li><p>En la isla de <strong>Biscoe</strong> habitan todos los pingüinos de la especie Gentoo y también hay algunos de la especie Adelie, pero no hay de la especie Chinstrap.</p></li>
<li><p>En la isla de <strong>Dream</strong> cohabitan pingüinos de las especies Adelie y Chinstrap, y es la isla en la que habitan todos los pingüinos de esta última especie.</p></li>
<li><p>Finalmente, en la isla de <strong>Torgersen</strong> solo habitan pingüinos de la especie Adelie.</p></li>
</ul>
<p>Esta distribución tan heterogénea de los pingüinos por isla nos indica que, muy posiblemente, las conclusiones que podamos extraer a partir de cómo se relaciona la isla con las demás variables sea similar a las que se puedan extraer a partir de cómo se relacionan con la especie, pues está muy sesgada por esta última.</p>
<p>Una vez visualizados algunos datos demográficos, estudiaremos cómo se relacionan las variables cuantitativas entre ellas y con las demás.</p>
</section>
</section>
<section id="variables-cuantitativas-por-especie" class="level2">
<h2 class="anchored" data-anchor-id="variables-cuantitativas-por-especie">Variables cuantitativas por especie</h2>
<p>En primer lugar, consideramos que puede ser interesante comparar las distintas medidas de los pingüinos entre especies. Para esto, primero visualizamos individualmente cada variable.</p>
<section id="comparación-una-a-una" class="level3">
<h3 class="anchored" data-anchor-id="comparación-una-a-una">Comparación una a una</h3>
<p>Para realizar esta comparación, utilizaremos una gráfica de violín para cada una de las variables cualitativas.</p>
<div class="quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="cell-output-display">
<p><img src="entrega1_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="cell-output-display">
<p><img src="entrega1_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="cell-output-display">
<p><img src="entrega1_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="cell-output-display">
<p><img src="entrega1_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
<p>En estos gráficos observamos un patrón común: Para cada medida, dos especies de pingüino suelen tener una distribución parecida, y la tercera es visiblemente distinta. Concretamente:</p>
<ul>
<li>Los pingüinos Adelie son, con diferencia, los que tienen el pico más corto.</li>
<li>Los Gentoo tienen, notablemente, el pico más fino, la aleta más larga y el mayor peso.</li>
</ul>
<p>Una vez visualizadas individualmente, puede ser interesante intentar, por un lado, cruzar las medidas entre ellas y, por el otro, relacionar esto con la especie.</p>
</section>
<section id="comparación-entre-ellas-y-por-especie" class="level3">
<h3 class="anchored" data-anchor-id="comparación-entre-ellas-y-por-especie">Comparación entre ellas y por especie</h3>
<p>Un gráfico de dispersión separado por colores nos permite cumplir ambos objetivos de esta sección al mismo tiempo.</p>
<p>Una vez visualizadas individualmente, puede ser interesante intentar, por un lado, cruzar las medidas entre ellas y, por el otro, relacionar esto con la especie. Un gráfico de dispersión separado por colores nos permite cumplir ambos objetivos al mismo tiempo.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="entrega1_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Vemos que los datos están bastante agrupados en el sentido que, dada una longitud y profundidad de pico, es posible inferir a qué especie de pingüino pertenece el hipotético espécimen: los Gentoo tienen el pico más largo y fino; los Adelie, más grueso y corto; y los Chinstrap se encuentran en un punto intermedio. Además, salvo en los pingüinos Adelie, los datos se ajustan medianamente bien a la recta de regresión de su especie.</p>
<p>Además de esta gráfica, es posible hacer <span class="math inline">\({{4}\choose{2}} =6\)</span> gráficos similares (en el sentido de explicar una medida en función de la otra), pero por motivos de brevedad representaremos únicamente la longitud de la aleta en función del peso.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="entrega1_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Observamos que, con estas variables, es difícil diferenciar a los Adelie de los Chinstrap, pero los Gentoo son claramente distintos, pues tienen, sensiblemente, la aleta más larga y una masa corporal mayor. De nuevo, excepto para los Adelie, los datos se ajustan medianamente bien a la recta de regresión.</p>
<p>Para finalizar con la sección de medidas por especie, nos ha parecido interesante hacer un gráfico de dispersión ligeramente más rico, en el que, además de dos medidas, se distinga por especie y por sexo. Para esto, representamos con colores las especies y con formas el sexo. Para variar respecto a las métricas, hemos representado la longitud del pico en función de la de la aleta:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="entrega1_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Considerando únicamente la especie, de nuevo están bastante diferenciadas según sus medidas: los Gentoo, como ya sabíamos, tienen la aleta más corta que los otros dos, y los Adelie tienen el pico más corto que los Chinstrap. Además, si nos fijamos en la forma de los puntos, podemos observar que, centrándonos en cada especie, los triángulos se suelen acumular arriba a la derecha y los círculos abajo a la izquierda. Esto nos dice que, por lo general, los machos tienen mayores longitudes de pico y aleta que las hembras. Los valores NA están relativamente dispersos dentro de cada especie.</p>
<p>Habría sido posible añadir formas según el sexo a cada uno de los gráficos que hemos hecho, pero esto habría complicado el entendimiento de todos ellos y consideramos más interesante estudiarlos por separado, y es lo que haremos en la siguiente sección.</p>
</section>
</section>
<section id="diferencias-entre-pingüinos-según-el-sexo" class="level2">
<h2 class="anchored" data-anchor-id="diferencias-entre-pingüinos-según-el-sexo">Diferencias entre pingüinos según el sexo</h2>
<p>Al igual que con la visualización por especie, utilizaremos un gráfico de violín para cada una de las métricas.</p>
<div class="quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="cell-output-display">
<p><img src="entrega1_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="cell-output-display">
<p><img src="entrega1_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="cell-output-display">
<p><img src="entrega1_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="cell-output-display">
<p><img src="entrega1_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
<p>Según los gráficos, parece que las tres especies presentan dimorfismo sexual: los machos suelen ser más grandes que las hembras respecto a todas las medidas.</p>
<p>Podríamos cruzar métricas y visualizar gráficos de dispersión similares a los que se han mostrado anteriormente por especie, pero las diferencias son claras estudiando las métricas una a una, y tal estudio no aportaría demasiada información adicional. Consideramos más interesante estudiar cómo se relacionan las variables cuantitativas con las isla y con el año.</p>
</section>
<section id="variables-cuantitativas-por-isla" class="level2">
<h2 class="anchored" data-anchor-id="variables-cuantitativas-por-isla">Variables cuantitativas por isla</h2>
<div class="quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="cell-output-display">
<p><img src="entrega1_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="cell-output-display">
<p><img src="entrega1_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="cell-output-display">
<p><img src="entrega1_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="cell-output-display">
<p><img src="entrega1_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
<p>En los diagramas anteriores, podemos observar que los pinguinos de la isla de Biscoe tienen un pico menos produnfo, una aleta más larga y pesan más. Esto se debe a que todos los ejemplares de la especie Gentoo habitan en esta isla y que tres de cada cuatro pinguinos de Biscoe son de esta especie.</p>
<p>Por otra parte, en la isla de Torgersen sólo hay pinguinos de la especie Adelie, lo cual se ve reflejado en que los ejemplares de esta isla tienen un pico más corto que los de las otras islas.</p>
<p>En último lugar, visualizaremos las variables cualitativas en función del año:</p>
</section>
<section id="métricas-por-año" class="level2">
<h2 class="anchored" data-anchor-id="métricas-por-año">Métricas por año</h2>
<div class="quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="cell-output-display">
<p><img src="entrega1_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="cell-output-display">
<p><img src="entrega1_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="cell-output-display">
<p><img src="entrega1_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="cell-output-display">
<p><img src="entrega1_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
<p>No podemos apreciar diferencias notables en ninguna variable cuantitativa respecto al año.</p>
</section>
<section id="conclusión-y-resumen" class="level2">
<h2 class="anchored" data-anchor-id="conclusión-y-resumen">Conclusión y resumen</h2>
<p>El conjunto de datos “penguins” es una fuente de información sobre tres especies de pingüinos diferentes: Adelie, Gentoo y Chinstrap. Estas especies habitan en tres islas diferentes: Torgersen, Biscoe y Dream. El conjunto de datos ofrece una variedad de medidas corporales, como la longitud y profundidad del pico, la longitud de la aleta y el peso corporal, lo que proporciona una visión detallada de las características físicas de estos pingüinos. Además, nos proporciona información sobre el sexo del pingüino y el año en que fue tomada cada muestra.</p>
<p>Una de las observaciones clave al explorar este conjunto de datos es la presencia de diferencias significativas entre las especies en términos de medidas corporales. Por ejemplo, los pingüinos Gentoo tienden a ser más grandes que las otras dos especies en cuanto a longitud de la aleta y peso corporal. Además, los pingüinos Adelie son los que tienen la longitud del pico más corta.</p>
<p>Además de las diferencias entre especies, el conjunto de datos también muestra variabilidad en la distribución de las especies por isla. Por ejemplo, en la isla Torgersen solo habitan los pingüinos de la especie Adelie. Mientrás que en la isla Biscoe no encontramos la especie Chinstrap y en la isla Dream no observamos la especie Gentoo.</p>
<p>El aspecto temporal se incorpora mediante el año en que se tomaron las medidas. No obstante, en nuestro estudio no hemos encontrado diferencias notables en las características de los pingüínos respecto al año.</p>
<p>Además, observamos claras diferencias físicas entre los machos y las hembras: los machos suelen ser más grandes que las hembras.</p>
<p>Un hecho a tener en cuenta es que, en general, los datos presentan pocos outliers, y los que hay no tienen valores exageradamente distintos al resto. Esto, sumado al hecho de que hay cierta variedad en los tipos de variables y en cómo se relacionan (a veces una variable influye en otras, y a veces no), hace que este conjunto de datos sea útil como conjunto de datos “test” en distintas aplicaciones de la estadística, así como lo hace el celebrado conjunto de datos <em>iris</em>.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>